### ISSUE TITLE
Example meta.search

### ISSUE THREAD

**Issue by ThanosDi** [Ivshti/stremio-addons#30]
Hello there and thank you for this awesome application.
I'd like to include to my addon the ability to search to an external api and stream the results.
For example I want to search on piratebay api via the stremio search and when I open a result to show the available magnet links.

I managed to add results as "cards" on the results but when I click on one I get "no information found about this"

Example code:

```
'meta.search': function(args, callback) {
		const query = args.query;
		return PirateBay.search(query, {
			orderBy: 'seeds',
			sortBy: 'desc'
		}).then(results => {
			const response = results.slice(0, 4).map( episode => {
				const {infoHash, announce } = magnet.decode(episode.magnetLink);
				const availability = episode.seeders == 0 ? 0 : episode.seeders < 5 ? 1 : 2;
				const detail = `${episode.name} S:${episode.seeders}`;
				return {
					id: episode.id,                                       // unique ID for the media, will be returned as "basic_id" in the request object later
					name: episode.name,                                          // title of media
					poster: 'http://thetvdb.com/banners/posters/78804-52.jpg',    // image link
					posterShape: 'regular',                                       // can also be 'landscape' or 'square'
					banner: 'http://thetvdb.com/banners/graphical/78804-g44.jpg', // image link
					genre: ['Entertainment'],
					isFree: 1,                                                    // some aren't
					popularity: 3831,                                             // the larger, the more popular this item is
					popularities: { basic: 3831 },                                // same as 'popularity'; use this if you want to provide different sort orders in your manifest
					type: 'series',
					stream: {
						infoHash,
						mapIdx: 0,
						name: 'PTB',
						title: detail,
						isFree: true,
						availability
					}
				};
			});
			return callback(null, {
				query,
				results: response
			});
		}).catch(err => {
			callback(err.message);
		});
	}
```

What should be a complete response object so when I click on a card to have the streams available?
Im guessing that `stream: {} ` object is not correct but I couldn't find anything on the documentations.

**Comment by jaruba** [comment]
The response from `meta.search` adds results to the Search, but it does not handle the information that will appear on the Details Page.

Once a result item is pressed in the Search, Stremio does a `meta.get` request with the ID you set for the item in `meta.search` (in your case `episode.id`). By replying to `meta.get` with (pretty much) the same object that you seem to reply to `meta.search` with, it should get you to the Detail Page successfully.

After that (seeing that you set the type to `series`), you should wait for a `stream.find` request with a set `season` and `episode` to reply with a stream obj.

**Comment by jaruba** [comment]
One more thing that should be mentioned is that `type: 'series'` also expects the `episodes` or `videos` properties set to the object when replying to `meta.get` otherwise it will show no episodes in the Episode List.

See [this page](https://github.com/Ivshti/stremio-addons/blob/master/docs/api/meta/meta.element.md) to understand what `meta.get` expects returned. And also look at the bottom of the same page under the `Video object` title to see what to include in the `episodes` or `videos` property.

**Comment by jaruba** [comment]
Series / movie metadata are usually handled internally in Stremio, this happens when the you use `imdb_id` as the id of the add-on. If `imdb_id` is used, then you only need to handle `stream.find` to attach your stream results to already existing series and movies inside the app. Otherwise (as seems to be your case), you need to handle `meta.search`, `meta.get`, `stream.find` and `meta.find` (this last one is optional, if implemented your add-on will also have it's own feed(s) in the Board)

**Comment by ThanosDi** [comment]
Thank you very much, that makes sense!
Appreciate you fast and detailed reply.

**Comment by jaruba** [comment]
Glad I could help, don't hesitate to ask more questions if you think things are unclear.

**Comment by ThanosDi** [comment]
Sorry to bother again but after some research I understood that this was not what I wanted to implement.
What I'm after is searching a custom query from the search page and adding magnet link results so when a user clicks a card to open the magnet link immediately.

The same operation as if I was pasting a magnet link on the search input.
For example 
![magnet link result](https://i.imgur.com/QNyCgii.jpg)

Do you think this is achievable atm? Thank you again for your time.

**Comment by jaruba** [comment]
From what I know, going directly to the player from the search page is not yet possible for any add-on that does not use youtube ids. This should be implemented, I've thought about it in the past also.

There is a way to _hack_ it in the current environment though, if you make a search response element for every result you have and set type to `movie` or `tv` for all your items, then the Detail Page that you sent the screenshot of would show available streams directly instead of videos / episodes (as movies and live streams have none).

So if you do the stream response for that `movie` or `tv` element id with it's magnet, it would make it available for the users in a more UI friendly manner.

I know it's not ideal, but i've seen this done successfully in the past by add-ons that only have videos, you could also not set the logo image for these items, in which case it will write the name in place of the logo.

But I would experiment with the `movie` and `tv` types if I were you. `tv` will probably suit this case best.

**Comment by ThanosDi** [comment]
Would it be too much to ask you for a sample search `tv` response object?
atm I return but nothing yet. 
```
return {
	id: `${episode.magnetLink}`, // or id: `id:${episode.magnetLink}`
	name: episode.name,
	poster: imgUrl,
	posterShape: 'regular',
	banner: imgUrl,
	genre: ['Entertainment'],
	isFree: 1,
	popularity: 3831,
	popularities: { basic: 3831 },
	type: 'tv'
};

```

**Comment by jaruba** [comment]
your object is correct, make sure you have `"types": ["tv"]` set in your add-on manifest

**Comment by jaruba** [comment]
Oh, it might also be a good idea to change the add-on port, and reload it in Stremio, as you changed it's supported type. I'm not sure if this is a requirement or not though, but it might be.

**Comment by ThanosDi** [comment]
Still no luck :disappointed: 
I can't understand how it is possible when I paste a magnet link to get the result I want but I cant make it happen programmatically.
Since I have the magnet link from the search result why I can;t force it to show the below result when I click a card.


![magnet link pasted](https://i.imgur.com/tYq982g.png)
*magnet link pasted*

Also how is it possible that a youtube channel can have the same results but magnet links can't
![youtube channel](https://i.imgur.com/fm67HS9.jpg)
*youtube channel*


Im almost sure that I miss something fundamental here thats why I bug you guys. Is there a way to make the above work from the search result? I essentially want to load complete season from a magnet link and stream each episode one by one(but coming from a search result, not pasting the magnet link)

Thank you again for your time and sorry if bothered you too much.

**Comment by jaruba** [comment]
It's becoming difficult to help you over github comments. Could you ping me on Gitter so we can have a real-time chat? https://gitter.im/jaruba

It might make things much simpler to solve
